* Indroduction

"The Great Gatsby" is based on classic novel by F.Scott Fitzgerold and directed by
the Oscar nominated film director "Baz Luhrmann". The story revolved around fictional
characters from New York elites on late twenties - the era of great financial prosperity
and Jazz age of music. Although this is a John Roe romantic classic drama, the red carpet
cinematography styles of story telling enables us to process this movie on lens of
causality and filters of derivatives that leads to "The great depression" during the
thirties and this reckless chasing of American dream keep coming back as of today
on the disguise of "effective alterism" as if -
"The greatest lesson from history is nobody takes lesson from it".

* Daisy's love

Daisy is a beautified woman with enchanted voice, she came from a privileged family based
on Louisville, Kentucky. It is quit obvious her family possesses mid-western contemporary
values and expectations. Gatsby, as a young military officer, stationed at Diasy's home
town where they first met and fall in love. Sooner he was deported to overseas and they
started to maintain long distance relationship by exchanging letters. As always, long
distance relationships are hard to maintain they move on with their life after
some years and Daisy gets married to a New York elite have their first child, a
daughter. Daisy was devastated right before her marriage after receiving a letter
from Gatsby that he is back to USA and he wanted to resume their relationship.

* overrated NYC stock exchange

Gatsby tried to buy back Daisy's love towards him same way contemporary companies
in New York stock exchange were inflating their price by "stock buy back" in disguise
like nowadays Adani Group not shaken by Hidenburg research. He was throwing outlandish
extravagant parties and made it common place to meet New York elite, influentials and
all sort of  people who knows because it was an open invitation. All these to lure Daisy
to one of their parties and have a prime time with Daisy of course in the mean time
her husband got distracted away from them with one his dream Hollywood actress. What a
cliche on the other hand this climax got shortened by the phone calls Gatsby needed to
 attain and the close door meeting with peoples like who fix 1950s world cup and calling
them shady would be an understatement. It is merely a consequence it's all happened when
Daisy was there first time in the party.

* Mystrious phone calls

During the parties and over the night we have seen mystorious phone calls where made
and intensity of calls can be quantified by getting facial expectations of the officials
that it was just not a mare request to receiving phone class in the middle of intence
climex. How important are those calls can be for that lets time machine to a decisive
a battle on 1815 - The Battle of Watterloo. It was Nepolien Banaports second attempts
after he managed to break through his departation form a island near vanis on his fist
defeat againt European Monarky lead by British empare. Nather Rothclild a renouned,
Rothclild, internation banker put his bet againt British Army for the unstoppable,
one of the greatest general - Nepolien got defeated so price of the British Bonds going to be
skyrocketted again. He took a u-turn overnight by spreading fake news that British
lose the war, as British people rush to sell out the assets and Rothclild managed to
purchase a huge amount of fortune cheap. This is why pediction and information goes
hand to hand, Gatsby's over phone calls represents advance information and his friendship
with fixers like shah represents ability of spreading fake news by twisting reality
before the next bell 10am on NYC exchange.



* fake it until make it
Racing tarbo charged Farriy in the middle of NY streets in the mean time
feeding faking information to audience, I wonder how Gatsby's dealer has gotten
the hold of chipsets and sensors to convert 1920s classic v8 engine to tarbocharged
ionized coulds of yellow streams to stick to the frame.
** faking up the humble begining
In a toxic corporate environment, it is possible that employees who receive little
attention from management and fly under the radar may harbor low morale and experience
negative effects on their mental health. This can create a situation where such employees
may feel disconnected or disengaged from the organization and may be more susceptible
to betraying the organization or taking advantage of opportunities for personal gain
when presented.
** true love doesn't care about riches
unlike beathy in the beast love in trnslated open up the huge library she wanted and visit
her birth place to discover what happened to her mother. gatsby love would be fakeing up him
self.
** you cannot change the past

* green light

It seems you are suggesting that Gatsby's pursuit of Daisy reflects a criticism
of the superficial and materialistic nature of the upper class, represented
by the "green light" across the river. This interpretation aligns with one
of the central themes of "The Great Gatsby," which explores the decadence,
shallowness, and moral corruption of the Jazz Age elite.

In the novel, Gatsby's infatuation with Daisy and his relentless pursuit of her
symbolize the allure and obsession with wealth and social status. He believes
that by winning Daisy's love and marrying her, he can transcend his humble origins
and become part of the privileged upper class. However, Gatsby's love for Daisy
is based on an idealized image rather than a deep understanding of her true character.

The "green light" that Gatsby sees across the river, situated on Daisy's dock,
represents his aspirations, dreams, and unattainable desires. It symbolizes his
longing for a romanticized past and his belief that wealth and success can make
him worthy of Daisy's love. Ultimately, Gatsby's pursuit of Daisy exposes the
emptiness and moral bankruptcy of the wealthy elite, as well as the destructive
power of illusions and unfulfilled dreams.

By linking Gatsby's pursuit of Daisy to the criticism of the green light and the
decadent society it represents, F. Scott Fitzgerald highlights the hollowness of
the American Dream and questions the values of the Roaring Twenties era.

* phychoanalysis by Emory university

** "Gatsby _ grand vition for his life restore everything just way before ..."

** Everybody interested how is gatsby who this millionier play boy next door before
kim kadesian grouge cluni before that there is Gatsby

** We have natural attraction towards wealth power beauty people thrilled by the lavish
lifestyle

** shame and greif
*** boy from a small town from noth decoda
*** ashamed of lower class upbringing
*** changed his name left army
*** become self maid man
*** shape molded againt
** shame vs gilt
*** shame something fundamental about self
*** react againt
*** Reaction formation shame of upbringing is exesgenated lavish display of welth
** Eye bocome powerful symbol
thought characters are relatively guild free they are afraid of been not for the
action
** complecated grif reaction
what happen in distorted grief reactoin time sort of stolled and try to recreate lost
time
*** Distorted gref reaction
when he first meet daisy after long time gatsby almost knock himself againt the
clock mental  ... get be to the age of 17.
** Idealization of daisy
*** inabality to see her flows and flows of this relationship

** can't rebuit the life once it was stuck not going back to past recreate their life
stuck not being able to move forward





* red carton cenematography
* effective Altruism
** fueled by sam bankman freed SBF
** the girl boss
elejabeth homes, the girl boss, beloved by clinton family and course at font page
of forbes sentenced 11 years of jail time for misguiding bunch of investors into putting
billons of dollar her company terranos into her delebared lie that her company can
diagonise 100s of deasise with just tiny drop of blood samples, build a 100 years of
simens company in a box, apparently fakeing boold test.
** Elonmask put twitter into chaos
** detained SBF ower nonfungable digital assets, once media darling turn out be fraud star,
stole billons dollar of customer fund.
made of
we are once told by the sociaty we are lucky have them
** understanding meth and ideology
entine sociacy tells
** phylontoropic atvisors

** end justinfying many means
*** acumolate large as cheratible chauses
**** stealing billon dollar cus fund
** longtermims map out milloun mitten
*** pottential possible collapse
*** foursee Ai destroy hmty

*** putting write of center of universe
*** elon mask
** charatable immarible, assotaric
** servitute of masses
** defer then all
real
** put our failth woth billerares
hav no
** maritocracy
** no

* Doesn't it also happening right now or does it

"I hope she'll be fool, that's the best thing a girl can be in this world,
beautiful little fool" - remarked by Daisy towards her daughter while feeling venerable,
oppressed for not standing up for herself that her husband Tom often
visit his mistress even care less to tag her cousin along with.
Tom's seeking violence against his mistress by no means is desire it's powerplay, it
about politics. It was very risky business for women to be getting involve then and
now specially their is a power differential where women could be subject to chocking as
 a part of the act. Once a woman said emotions are so instance against doing this
 she often found herself in the floor of bathroom vomiting and her mind is a lot weaker
 than she thought it is.






* 95%-5%, the house of cards
** something about having children forces you think about future
*** don't have family hv our kids left ur community don't have
solid inform voices left home 8 , took on there live 3000 miles away
onthere own
** kin groups are protective
** deisy does have her consent she played her part


* conclution
we need to set our difference aside to deal with moral bankrupct people who things
themself either son of gods and gods who are divined to rull huminith either by domant
rase theroy,  implerisom other type of fasism like you will own night and you will be happay
other wise we are going to kill ourself out of grief or intensive pursure they are putting on
us by controlling everything we have starting with of cell phone.
